title: Purpose and properties of the JSKOS data format for knowledge graphs
subtitle: SWIB 2025 conference
date: 2025-11-19
author: Jakob Vo√ü

format:
  revealjs:
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: vzglogo.png
    incremental: true
    css: style.css
