title: JSKOS
subtitle: ...
author: Jakob Vo√ü

format:
  revealjs:
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: vzglogo.png
    incremental: true
    css: style.css
